##############################################################################
#  _____                    _   _           _        __  __ _ _              #
# |  __ \                  | \ | |         | |      |  \/  (_) |             #
# | |__) |__   __ _  ___   |  \| | ___   __| | ___  | \  / |_| |_ _ __ ___   #
# |  ___/ _ \ / _` |/ _ \  | . ` |/ _ \ / _` |/ _ \ | |\/| | | __| '_ ` _ \  #
# | |  | (_) | (_| | (_) | | |\  | (_) | (_| |  __/ | |  | | | |_| | | | | | #
# |_|   \___/ \__, |\___/  |_| \_|\___/ \__,_|\___| |_|  |_|_|\__|_| |_| |_| #
#              __/ |                                                         #
#             |___/                                                          #
##############################################################################

# Proxy config.
# - port=8888 is the port the proxy will listen to
proxy:
    active: true
    port: 8888

# Web UI config.
# - port=8080 is the port the ui will listen to
# - if upload=true, publish an upload enpoint to allow live upload of requests
ui:
    active: true
    port: 8080
    upload: false

# For session analysing
# replayhashing=true will try to validate hashing against current bossland api
# hashendpoint: bossland endpoint
# hashkey: hashkey from bossland
# hashkeyrpm: rpm, used to calculte speed of check
analysis:
    replayhashing: false
    hashendpoint: http://pokehash.buddyauth.com/api/v137_1/hash
    hashkey: your-key
    hashkeyrpm: 150

# Logging config
# - level=info, log level (debug, info, warn, error)
# - file=null, if set, log to a file 
logger: 
    level: info
